language: php

php:
  - 7.3
  - 7.4

sudo: false

install:
  - travis_retry composer install --no-interaction --prefer-source
  - composer require satooshi/php-coveralls

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_success: php vendor/bin/coveralls
